### ISSUE TITLE
Forced perks aren't shown as options in gear builder

### ISSUE THREAD

**Issue by Sup3rlativ3** [giniedp/nw-buddy#1] opened 2022-10-20 11:02 UTC
Hi,

Firstly, thanks very much for the tool, I think it's fantastic.

I have found an understandable bug though.

There are some perks that must be forced and so aren't in the normal buckets and therefore can't be selected.

Examples:

Orichalcum Great Axe - Unable to choose an attunement perk.
Colorful Kraken Boots- Unable to choose resilient perk.

I have found some others such as not being able to choose a gem slot for the old jewelry too.

Please let me know if you need any more information.

**Comment by giniedp** [comment] 2022-10-20 11:23
Thanks for the report, chust checked and i can confirm that it is an issue.

**Comment by giniedp** [comment] 2022-10-22 00:38
@Sup3rlativ3 if you have weapons in your inventory that you can not replicate in the gear builder, please share a screenshot.

I reviewed some items and compared to nwdb.info. So far the options do match with the listings on nwdb.info.

For the Kraken Boots i can not find a valid connection with the resilient perk. If such an item exists in the game then there must be a logik that i can not deduce from the data. At least right now.

Also there is an issue with the **Old ring**. There are two versions
https://nwdb.info/db/item/RingDropT5 seems to be fine
https://nwdb.info/db/item/RingCastT5 comes from Gypsum Cast and has a 70% chance on the second perk slot but references Weapon perks

Usually if you weild a gem on to a weapon, you get the weapon perks. And on armor you get the armor perks. That ring references Weapon perks which is invalid

**Comment by Sup3rlativ3** [comment] 2022-10-22 02:28
I've put these in the discord but I'll put them here as well for reference.
![Kraken boots](https://user-images.githubusercontent.com/1555043/197315057-ff997867-8728-40ba-912d-403233b9b6ea.png)
![Attunement Axe](https://user-images.githubusercontent.com/1555043/197315063-e89782ab-8609-42a0-8d6d-e43a0c13d273.png)

**Comment by giniedp** [comment] 2022-10-22 09:41
yes, trying a different approach now. Will open up all applicable perks for the given slot even if they are not directly referenced by the item in question. Looks good now.

**Comment by giniedp** [comment] 2022-10-23 15:44
I'll close this for now. If any perk does not work with recent release, feel free to reopen or issue another ticket.

**Closed by giniedp** 2022-10-23 15:44 UTC
Labels: bug
